[project]
name = "simikit"
version = "0.0.1"
description = "Image Similarity Toolkit in Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv]
build-constraint-dependencies = ["setuptools==60.0.0"]