name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    name: uv publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv with python3.13
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
