# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: simikit run tests

on:
  push:
    paths:
      - 'simikit/*'
  pull_request:
    paths:
      - 'simikit/*'

jobs:
  uv-tests:
    name: uv tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv with python${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --group test

      - name: Run tests with coverage
        run: uv run pytest -s -x --cov=simikit -vv --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: tests
          name: simikit Tests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          
