# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ruff and cov check

on:
  push:
    paths:
      - 'simikit/*'
  pull_request:
    paths:
      - 'simikit/*'
  workflow_dispatch:

jobs:
  uv-tests:
    name: uv ruff and cov check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv with python3.13
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Install the project
        run: uv sync --group ruff

      - name: Run ruff check
        run: uv run ruff check .

#      - name: Run tests with coverage
#        run: uv run pytest -s -x --cov=simikit -vv --cov-report=xml
#
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v5
#        with:
#          file: ./coverage.xml
#          flags: tests
#          name: simikit Tests
#          fail_ci_if_error: true
#          token: ${{ secrets.CODECOV_TOKEN }}
